### ISSUE TITLE
Plano de risco

### ISSUE THREAD

**Issue by rg3915** [rg3915/new_way_project#20]
Plano de risco

**Comment by rg3915** [comment]
pode ser você?

**Comment by gugool** [comment]
Pode sim, plano de risco e apf?

--- Mensagem Original ---

De: "Regis da Silva" <notifications@github.com>
Enviado: 14 de março de 2015 13:02
Para: "rg3915/new_way_project" <new_way_project@noreply.github.com>
Cc: "gugool" <gugool_@hotmail.com>
Assunto: Re: [new_way_project] Plano de risco (#20)

pode ser você?

---

**Comment by rg3915** [comment]
ok

**Comment by gugool** [comment]
Regis, você tem algum modelo de plano de risco ?

**Comment by rg3915** [comment]
Não tenho, favor ver o que tem no blackboard.
