### ISSUE TITLE
Ver os modelos

### ISSUE THREAD

**Issue by rg3915** [rg3915/new_way_project#21]
https://github.com/rg3915/new_way_project/blob/master/modelagem/models01.txt

**Comment by rafaelcarneo** [comment]
Cara .. vê se é isso mesmo que você quer !
Vai demorar 1 ano pra pegar todos os modelos dos carros com foto kkkkkk
Vê se é isso mesmo

Date: Sat, 14 Mar 2015 06:53:45 -0700

**Comment by rg3915** [comment]
Cancelado
