### ISSUE TITLE
Segunda entrega

### ISSUE THREAD

**Issue by rg3915** [rg3915/new_way_project#33]
1) Elabore um levantamento dos principais requisitos (funcionais e não funcionais);
2) Faça uma especificação de caso de uso dos principais requisitos;
3) Elabore um diagrama de caso de uso;
4) Elabore matriz de rastreabilidade relacionado UCxRN, UCxRF, UCxMSG, UCxRNF
5) Elabore um plano de teste e Casos de Testes dos principais aspectos que o sistema deve ser testado, bem como um diagrama de caso de teste do caso de uso abordado nos testes;
6) Elabore um diagrama de classe de negócio, modelando as principais classes de negócio;
7) Elabore protótipo das principais telas(seja em html, imagem ou outro recurso visual);
8) Documentar os campos do protótipo o documento "Elementos do Protótipo"

**Comment by rg3915** [comment]
Estou fazendo o item 7, layouts.

**Comment by Aciole** [comment]
Eu fiz o item6, por favor revisem.

**Comment by rg3915** [comment]
Eu fiz os layouts do item 8.
https://github.com/rg3915/new_way_project/tree/master/documentacao/segunda_entrega/layout
Estou enviando por email também, favor me informar se faltar alguma coisa.
