### ISSUE TITLE
Relatório com consultas SQL

### ISSUE THREAD

**Issue by rg3915** [rg3915/new_way_project#41]
Favor escrever os comandos SQL para gerar os seguintes relatórios:

veículos mais consultados por faixa de idade
veículos mais consultados por sexo
veículos mais consultados por região
concessionárias que mais venderam
veículos mais vendidos

**Comment by rg3915** [comment]
São 3 tabelas

interessados
veiculos
pedidos


veiculos mais consultaodos por faixa de idade

SELECT 		count(*) 
FROM 		dbo.tabela 
where 		faixa_idade >= 1 
and 		faixa_idade < 5



SELECT 		count(veiculos) 
FROM 		dbo.tabela1	a 
inner join	dbo.tabela2	b
on		a.id = b.id	
where 		b.faixa_idade >= 1 
and 		b.faixa_idade < 5

SELECT 		count(veiculos) 
FROM 		dbo.tabela1	a 
inner join	dbo.tabela2	b
on		a.id = b.id	
where 		b.faixa_idade BETWEEN 1 AND 5

**Comment by rafaelcarneo** [comment]
Fala .. Beleza?

Até domingo eu mando tudo pra você ! Falei com o professor e ele disse que precisa de muito !
Já te passo os códigos do banco 

Enviado do meu iPhone

**Comment by rg3915** [comment]
Só falta veículos mais consultados por faixa de idade

**Comment by rg3915** [comment]
Cancelado
